"""Catalogue produits Chutex Care.

Repris à l'identique du backend FastAPI Mongo (`shop_routes.py`).
À garder synchronisé tant que les deux backends coexistent.
"""
from __future__ import annotations

PRODUCTS: dict[str, dict] = {
    "elder-vest": {
        "id": "elder-vest", "category": "devices",
        "name": "Gilet Elder", "name_en": "Elder Vest",
        "price": 879.00, "type": "one-time",
        "image": "https://chutex-innovation.com/cdn/shop/files/chutex-elder-airbag-vest-made-in-france-front-side.png?v=1752931654&width=400",
        "variants": [
            {"id": "elder-vest-s", "label": "Taille S", "label_en": "Size S"},
            {"id": "elder-vest-m", "label": "Taille M", "label_en": "Size M"},
            {"id": "elder-vest-l", "label": "Taille L", "label_en": "Size L"},
            {"id": "elder-vest-xl", "label": "Taille XL", "label_en": "Size XL"},
        ],
    },
    "elder-teleassistance": {
        "id": "elder-teleassistance", "category": "bundles",
        "name": "Elder + Teleassistance 24/7", "name_en": "Elder + Teleassistance 24/7",
        "price": 879.00, "subscription_price": 29.90, "type": "hybrid",
        "image": "https://chutex-innovation.com/cdn/shop/files/chutex-elder-airbag-vest-made-in-france-front-side.png?v=1752931654&width=400",
        "variants": [
            {"id": "elder-tele-s", "label": "Taille S", "label_en": "Size S"},
            {"id": "elder-tele-m", "label": "Taille M", "label_en": "Size M"},
            {"id": "elder-tele-l", "label": "Taille L", "label_en": "Size L"},
            {"id": "elder-tele-xl", "label": "Taille XL", "label_en": "Size XL"},
        ],
    },
    "elio-standard": {"id": "elio-standard", "category": "subscriptions",
        "name": "Elio — Abonnement Standard", "name_en": "Elio — Standard Plan",
        "price": 0, "subscription_price": 24.90, "type": "subscription",
        "desc": "Suivi sante continu, alertes preventives, app Chutex.",
        "desc_en": "Continuous health monitoring, preventive alerts, Chutex app.",
        "image": "/images/products/elio-card.webp", "variants": []},
    "elio-sport": {"id": "elio-sport", "category": "subscriptions",
        "name": "Elio — Abonnement Sport", "name_en": "Elio — Sport Plan",
        "price": 0, "subscription_price": 29.90, "type": "subscription",
        "desc": "Standard + coaching sportif, VO2max, recuperation, programmes personnalises.",
        "desc_en": "Standard + sports coaching, VO2max, recovery, personalized programs.",
        "image": "/images/products/elio-card.webp", "variants": []},
    "elio-physio": {"id": "elio-physio", "category": "subscriptions",
        "name": "Elio — Abonnement Physio", "name_en": "Elio — Physio Plan",
        "price": 0, "subscription_price": 34.90, "type": "subscription",
        "desc": "Standard + suivi reeducation, partage donnees kinesitherapeute, exercices guides.",
        "desc_en": "Standard + rehabilitation tracking, physio data sharing, guided exercises.",
        "image": "/images/products/elio-card.webp", "variants": []},
    "elio-care": {"id": "elio-care", "category": "subscriptions",
        "name": "Elio — Abonnement Care", "name_en": "Elio — Care Plan",
        "price": 0, "subscription_price": 39.90, "type": "subscription",
        "desc": "Tout inclus : teleassistance 24/7, geolocalisation, coordination secours, support prioritaire.",
        "desc_en": "All-inclusive: 24/7 teleassistance, geolocation, emergency coordination, priority support.",
        "image": "/images/products/elio-card.webp", "variants": []},
    "vita-scale": {"id": "vita-scale", "category": "devices",
        "name": "Balance Vita", "name_en": "Vita Scale",
        "price": 229.00, "type": "one-time",
        "image": "https://static.prod-images.emergentagent.com/jobs/48e5eb31-c61a-4fb1-be42-94e61a127565/images/99cc1301d04c1c60a23347cfabdb0335b694b42162bb12541d38ea6638ebb23d.png",
        "variants": []},
    "dorsi-cushion": {"id": "dorsi-cushion", "category": "devices",
        "name": "Coussin Dorsi", "name_en": "Dorsi Cushion",
        "price": 349.00, "type": "one-time",
        "desc": "Coussin connecte de prevention lombaire. Bilan de mobilite, exercices guides, suivi progression.",
        "desc_en": "Connected lumbar prevention cushion. Mobility assessment, guided exercises, progress tracking.",
        "image": "/images/products/dorsi-card.webp", "variants": []},
    "bundle-elio-elder": {"id": "bundle-elio-elder", "category": "bundles",
        "name": "Pack Elio + Elder — Teleassistance 24/7",
        "name_en": "Elio + Elder Bundle — 24/7 Teleassistance",
        "price": 879.00, "subscription_price": 79.90, "type": "hybrid",
        "desc": "Le pack complet : gilet airbag + bracelet + teleassistance 24/7.",
        "desc_en": "The complete pack: airbag vest + bracelet + 24/7 teleassistance.",
        "image": "https://chutex-innovation.com/cdn/shop/files/chutex-elder-airbag-vest-made-in-france-front-side.png?v=1752931654&width=400",
        "variants": [
            {"id": "bundle-elio-elder-s", "label": "Taille S (Gilet)", "label_en": "Size S (Vest)"},
            {"id": "bundle-elio-elder-m", "label": "Taille M (Gilet)", "label_en": "Size M (Vest)"},
            {"id": "bundle-elio-elder-l", "label": "Taille L (Gilet)", "label_en": "Size L (Vest)"},
            {"id": "bundle-elio-elder-xl", "label": "Taille XL (Gilet)", "label_en": "Size XL (Vest)"},
        ]},
    "cartouche-helium-x2": {"id": "cartouche-helium-x2", "category": "accessories",
        "name": "Cartouches d'helium (x2)", "name_en": "Helium Cartridges (x2)",
        "price": 39.90, "type": "one-time",
        "desc": "Lot de 2 cartouches de recharge pour les cellules airbag du gilet Elder.",
        "desc_en": "Pack of 2 refill cartridges for Elder vest airbag cells.",
        "image": "https://chutex-innovation.com/cdn/shop/files/chutex-elder-airbag-vest-made-in-france-front-side.png?v=1752931654&width=400",
        "variants": []},
    "cartouche-helium-x4": {"id": "cartouche-helium-x4", "category": "accessories",
        "name": "Cartouches d'helium (x4)", "name_en": "Helium Cartridges (x4)",
        "price": 69.90, "type": "one-time",
        "desc": "Lot de 4 cartouches de recharge — prix avantageux.",
        "desc_en": "Pack of 4 refill cartridges — best value.",
        "image": "https://chutex-innovation.com/cdn/shop/files/chutex-elder-airbag-vest-made-in-france-front-side.png?v=1752931654&width=400",
        "variants": []},
    "chargeur-elder": {"id": "chargeur-elder", "category": "accessories",
        "name": "Chargeur USB-C Elder", "name_en": "Elder USB-C Charger",
        "price": 19.90, "type": "one-time",
        "desc": "Chargeur de remplacement pour le gilet Elder.",
        "desc_en": "Replacement charger for the Elder vest.",
        "image": "https://chutex-innovation.com/cdn/shop/files/chutex-elder-airbag-vest-made-in-france-front-side.png?v=1752931654&width=400",
        "variants": []},
    "chargeur-elio": {"id": "chargeur-elio", "category": "accessories",
        "name": "Chargeur magnetique Elio", "name_en": "Elio Magnetic Charger",
        "price": 14.90, "type": "one-time",
        "desc": "Chargeur magnetique de remplacement pour le bracelet Elio.",
        "desc_en": "Replacement magnetic charger for the Elio bracelet.",
        "image": "/images/products/elio-card.webp", "variants": []},
    "bracelet-elio-spare": {"id": "bracelet-elio-spare", "category": "accessories",
        "name": "Bracelet Elio — Bracelet de rechange", "name_en": "Elio — Spare Strap",
        "price": 24.90, "type": "one-time",
        "desc": "Bracelet en silicone medical de rechange (3 couleurs).",
        "desc_en": "Replacement medical silicone strap (3 colors).",
        "image": "/images/products/elio-card.webp",
        "variants": [
            {"id": "bracelet-spare-noir", "label": "Noir", "label_en": "Black"},
            {"id": "bracelet-spare-gris", "label": "Gris", "label_en": "Grey"},
            {"id": "bracelet-spare-bleu", "label": "Bleu marine", "label_en": "Navy blue"},
        ]},
    "housse-elder": {"id": "housse-elder", "category": "accessories",
        "name": "Housse textile Elder", "name_en": "Elder Textile Cover",
        "price": 49.90, "type": "one-time",
        "desc": "Housse de remplacement lavable en machine pour le gilet Elder.",
        "desc_en": "Machine-washable replacement cover for the Elder vest.",
        "image": "https://chutex-innovation.com/cdn/shop/files/chutex-elder-airbag-vest-made-in-france-front-side.png?v=1752931654&width=400",
        "variants": [
            {"id": "housse-elder-s", "label": "Taille S", "label_en": "Size S"},
            {"id": "housse-elder-m", "label": "Taille M", "label_en": "Size M"},
            {"id": "housse-elder-l", "label": "Taille L", "label_en": "Size L"},
            {"id": "housse-elder-xl", "label": "Taille XL", "label_en": "Size XL"},
        ]},
}
